// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (email, normalized_email, display_name, avatar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, email, normalized_email, display_name, avatar_url, status, created_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	Email           pgtype.Text `json:"email"`
	NormalizedEmail pgtype.Text `json:"normalized_email"`
	DisplayName     string      `json:"display_name"`
	AvatarUrl       pgtype.Text `json:"avatar_url"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Email,
		arg.NormalizedEmail,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createAccountIdentity = `-- name: CreateAccountIdentity :one
INSERT INTO account_identities (
    account_id,
    provider,
    provider_subject,
    email,
    normalized_email,
    email_verified,
    password_hash
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, account_id, provider, provider_subject, email, normalized_email, email_verified, password_hash, created_at, updated_at
`

type CreateAccountIdentityParams struct {
	AccountID       pgtype.UUID `json:"account_id"`
	Provider        string      `json:"provider"`
	ProviderSubject string      `json:"provider_subject"`
	Email           pgtype.Text `json:"email"`
	NormalizedEmail pgtype.Text `json:"normalized_email"`
	EmailVerified   bool        `json:"email_verified"`
	PasswordHash    pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateAccountIdentity(ctx context.Context, arg CreateAccountIdentityParams) (AccountIdentity, error) {
	row := q.db.QueryRow(ctx, createAccountIdentity,
		arg.AccountID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Email,
		arg.NormalizedEmail,
		arg.EmailVerified,
		arg.PasswordHash,
	)
	var i AccountIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.NormalizedEmail,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAccountSession = `-- name: CreateAccountSession :one
INSERT INTO account_sessions (account_id, token_hash, user_agent, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, token_hash, user_agent, expires_at, revoked_at, created_at
`

type CreateAccountSessionParams struct {
	AccountID pgtype.UUID        `json:"account_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent string             `json:"user_agent"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAccountSession(ctx context.Context, arg CreateAccountSessionParams) (AccountSession, error) {
	row := q.db.QueryRow(ctx, createAccountSession,
		arg.AccountID,
		arg.TokenHash,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i AccountSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findAccountBySessionTokenHash = `-- name: FindAccountBySessionTokenHash :one
SELECT
    a.id,
    a.email,
    a.normalized_email,
    a.display_name,
    a.avatar_url,
    a.status,
    a.created_at,
    a.updated_at,
    a.deleted_at
FROM account_sessions s
JOIN accounts a ON a.id = s.account_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
  AND a.deleted_at IS NULL
  AND a.status = 'active'
`

func (q *Queries) FindAccountBySessionTokenHash(ctx context.Context, tokenHash string) (Account, error) {
	row := q.db.QueryRow(ctx, findAccountBySessionTokenHash, tokenHash)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findActiveAccountByNormalizedEmail = `-- name: FindActiveAccountByNormalizedEmail :one
SELECT id, email, normalized_email, display_name, avatar_url, status, created_at, updated_at, deleted_at
FROM accounts
WHERE normalized_email = $1
  AND deleted_at IS NULL
  AND status = 'active'
`

func (q *Queries) FindActiveAccountByNormalizedEmail(ctx context.Context, normalizedEmail pgtype.Text) (Account, error) {
	row := q.db.QueryRow(ctx, findActiveAccountByNormalizedEmail, normalizedEmail)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findEmailIdentityWithAccount = `-- name: FindEmailIdentityWithAccount :one
SELECT
    ai.id,
    ai.account_id,
    ai.provider,
    ai.provider_subject,
    ai.email,
    ai.normalized_email,
    ai.email_verified,
    ai.password_hash,
    ai.created_at,
    ai.updated_at,
    a.id AS account_id_2,
    a.email AS account_email,
    a.normalized_email AS account_normalized_email,
    a.display_name AS account_display_name,
    a.avatar_url AS account_avatar_url,
    a.status AS account_status,
    a.created_at AS account_created_at,
    a.updated_at AS account_updated_at,
    a.deleted_at AS account_deleted_at
FROM account_identities ai
JOIN accounts a ON a.id = ai.account_id
WHERE ai.provider = 'email'
  AND ai.normalized_email = $1
  AND a.deleted_at IS NULL
  AND a.status = 'active'
`

type FindEmailIdentityWithAccountRow struct {
	ID                     pgtype.UUID        `json:"id"`
	AccountID              pgtype.UUID        `json:"account_id"`
	Provider               string             `json:"provider"`
	ProviderSubject        string             `json:"provider_subject"`
	Email                  pgtype.Text        `json:"email"`
	NormalizedEmail        pgtype.Text        `json:"normalized_email"`
	EmailVerified          bool               `json:"email_verified"`
	PasswordHash           pgtype.Text        `json:"password_hash"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	AccountID2             pgtype.UUID        `json:"account_id_2"`
	AccountEmail           pgtype.Text        `json:"account_email"`
	AccountNormalizedEmail pgtype.Text        `json:"account_normalized_email"`
	AccountDisplayName     string             `json:"account_display_name"`
	AccountAvatarUrl       pgtype.Text        `json:"account_avatar_url"`
	AccountStatus          string             `json:"account_status"`
	AccountCreatedAt       pgtype.Timestamptz `json:"account_created_at"`
	AccountUpdatedAt       pgtype.Timestamptz `json:"account_updated_at"`
	AccountDeletedAt       pgtype.Timestamptz `json:"account_deleted_at"`
}

func (q *Queries) FindEmailIdentityWithAccount(ctx context.Context, normalizedEmail pgtype.Text) (FindEmailIdentityWithAccountRow, error) {
	row := q.db.QueryRow(ctx, findEmailIdentityWithAccount, normalizedEmail)
	var i FindEmailIdentityWithAccountRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.NormalizedEmail,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID2,
		&i.AccountEmail,
		&i.AccountNormalizedEmail,
		&i.AccountDisplayName,
		&i.AccountAvatarUrl,
		&i.AccountStatus,
		&i.AccountCreatedAt,
		&i.AccountUpdatedAt,
		&i.AccountDeletedAt,
	)
	return i, err
}

const findIdentityWithAccount = `-- name: FindIdentityWithAccount :one
SELECT
    ai.id,
    ai.account_id,
    ai.provider,
    ai.provider_subject,
    ai.email,
    ai.normalized_email,
    ai.email_verified,
    ai.password_hash,
    ai.created_at,
    ai.updated_at,
    a.id AS account_id_2,
    a.email AS account_email,
    a.normalized_email AS account_normalized_email,
    a.display_name AS account_display_name,
    a.avatar_url AS account_avatar_url,
    a.status AS account_status,
    a.created_at AS account_created_at,
    a.updated_at AS account_updated_at,
    a.deleted_at AS account_deleted_at
FROM account_identities ai
JOIN accounts a ON a.id = ai.account_id
WHERE ai.provider = $1
  AND ai.provider_subject = $2
  AND a.deleted_at IS NULL
  AND a.status = 'active'
`

type FindIdentityWithAccountParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

type FindIdentityWithAccountRow struct {
	ID                     pgtype.UUID        `json:"id"`
	AccountID              pgtype.UUID        `json:"account_id"`
	Provider               string             `json:"provider"`
	ProviderSubject        string             `json:"provider_subject"`
	Email                  pgtype.Text        `json:"email"`
	NormalizedEmail        pgtype.Text        `json:"normalized_email"`
	EmailVerified          bool               `json:"email_verified"`
	PasswordHash           pgtype.Text        `json:"password_hash"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	AccountID2             pgtype.UUID        `json:"account_id_2"`
	AccountEmail           pgtype.Text        `json:"account_email"`
	AccountNormalizedEmail pgtype.Text        `json:"account_normalized_email"`
	AccountDisplayName     string             `json:"account_display_name"`
	AccountAvatarUrl       pgtype.Text        `json:"account_avatar_url"`
	AccountStatus          string             `json:"account_status"`
	AccountCreatedAt       pgtype.Timestamptz `json:"account_created_at"`
	AccountUpdatedAt       pgtype.Timestamptz `json:"account_updated_at"`
	AccountDeletedAt       pgtype.Timestamptz `json:"account_deleted_at"`
}

func (q *Queries) FindIdentityWithAccount(ctx context.Context, arg FindIdentityWithAccountParams) (FindIdentityWithAccountRow, error) {
	row := q.db.QueryRow(ctx, findIdentityWithAccount, arg.Provider, arg.ProviderSubject)
	var i FindIdentityWithAccountRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.NormalizedEmail,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID2,
		&i.AccountEmail,
		&i.AccountNormalizedEmail,
		&i.AccountDisplayName,
		&i.AccountAvatarUrl,
		&i.AccountStatus,
		&i.AccountCreatedAt,
		&i.AccountUpdatedAt,
		&i.AccountDeletedAt,
	)
	return i, err
}

const revokeAccountSession = `-- name: RevokeAccountSession :exec
UPDATE account_sessions
SET revoked_at = now()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAccountSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeAccountSession, tokenHash)
	return err
}

const revokeAllAccountSessions = `-- name: RevokeAllAccountSessions :exec
UPDATE account_sessions
SET revoked_at = now()
WHERE account_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllAccountSessions(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllAccountSessions, accountID)
	return err
}

const softDeleteAccount = `-- name: SoftDeleteAccount :exec
UPDATE accounts
SET status = 'deleted',
    deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAccount, id)
	return err
}
