// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET status = 'running',
    attempts = attempts + 1,
    locked_at = now(),
    locked_by = $1,
    updated_at = now()
WHERE id = (
    SELECT id
    FROM jobs
    WHERE status = 'queued'
        AND available_at <= now()
    ORDER BY available_at, created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, type, payload, status, attempts, max_attempts, available_at, locked_at, locked_by, last_error, created_at, updated_at
`

func (q *Queries) ClaimJob(ctx context.Context, lockedBy pgtype.Text) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, lockedBy)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs
SET status = 'succeeded',
    updated_at = now()
WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (type, payload, available_at)
VALUES ($1, $2, $3)
RETURNING id, type, payload, status, attempts, max_attempts, available_at, locked_at, locked_by, last_error, created_at, updated_at
`

type EnqueueJobParams struct {
	Type        string             `json:"type"`
	Payload     []byte             `json:"payload"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, enqueueJob, arg.Type, arg.Payload, arg.AvailableAt)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs
SET status = CASE WHEN attempts >= max_attempts THEN 'failed' ELSE 'queued' END,
    last_error = $2,
    available_at = $3,
    locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
WHERE id = $1
`

type FailJobParams struct {
	ID          int64              `json:"id"`
	LastError   pgtype.Text        `json:"last_error"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob, arg.ID, arg.LastError, arg.AvailableAt)
	return err
}
