// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Document struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	SourceUri pgtype.Text        `json:"source_uri"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DocumentChunk struct {
	ID         pgtype.UUID        `json:"id"`
	DocumentID pgtype.UUID        `json:"document_id"`
	ChunkIndex int32              `json:"chunk_index"`
	Content    string             `json:"content"`
	Embedding  pgvector.Vector    `json:"embedding"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID          int64              `json:"id"`
	Type        string             `json:"type"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	MaxAttempts int32              `json:"max_attempts"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	LockedAt    pgtype.Timestamptz `json:"locked_at"`
	LockedBy    pgtype.Text        `json:"locked_by"`
	LastError   pgtype.Text        `json:"last_error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
