// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimJob(ctx context.Context, lockedBy pgtype.Text) (Job, error)
	CompleteJob(ctx context.Context, id int64) error
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error)
	FailJob(ctx context.Context, arg FailJobParams) error
	Ping(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
